### ISSUE TITLE
Laravel Vite

### ISSUE THREAD

**Issue by icreaciones** [genesisweb/valet-linux-plus#102]
Hi guys,

I have successfully installed Valet Linux Plus on a remote server. I've set up a website and everything is working fine—I can access it perfectly from my machine. However, when I configure Vite with a clean installation of Laravel, it doesn't work.

I've configured Vite to have the same host as the "laravel.test" application. I've started the server with "npm run dev" and it launches perfectly. However, the URL generated by Laravel Vite as the server doesn't receive a response. It's as if port 5173 is not responding or not properly configured with Nginx or something similar.

![image](https://github.com/genesisweb/valet-linux-plus/assets/97635999/6f4366b7-6804-40b0-bee2-236e7c36360a)
![image](https://github.com/genesisweb/valet-linux-plus/assets/97635999/abf5b5a8-7e68-4669-9de8-2196b64f759a)
![image](https://github.com/genesisweb/valet-linux-plus/assets/97635999/d933c3e1-143e-4546-9e21-f53749d887ab)

Thankssss¡¡¡¡

**Comment by uttamrabadiya** [comment]
@icreaciones 

I believe we have same issue closed recently and it was resolved by Laravel's vite configuration. Please review below issue once.

Related issue: https://github.com/genesisweb/valet-linux-plus/issues/104

Thanks!
