### ISSUE TITLE
Add Gnome WEB browser (epiphany) ssl support

### ISSUE THREAD

**Issue by MordiSacks** [genesisweb/valet-linux-plus#103]
Her are instructions from gnome
https://help.gnome.org/users/epiphany/stable/cert.html.en

seems very straightforward 

I will attempt PR my self
I find this browser very useful for testing safari (IOS) compatibility

I might also attempt to fix the FireFox issue #100

**Comment by uttamrabadiya** [comment]
@MordiSacks Nice suggestion, we will see if we can find something similar to this.

**Comment by uttamrabadiya** [comment]
@MordiSacks 

We've just fixed SSL support for Firefox browser, we are still working to fix it system wide solution.

Thank you!
