### ISSUE TITLE
Linux Mint/Valet_- v1.6.6 - Laravel/Vue installation - Error with resources

### ISSUE THREAD

**Issue by CarlOgden1967** [genesisweb/valet-linux-plus#104]
Hi

I've got a brand new install of Laravel and am following tutorial instructions to enable a new laravel/vue3 website. 

However, when I've got to the end of the tutorial and open the website, I get the text on the main webpage but nothing from a component.

When I inspect the console, I get the following 3 messages (there is 4 but the fourth is the favicon which I don't have yet!)

Failed to load resource: net::ERR_BLOCKED_BY_CLIENT client:1
Failed to load resource: net::ERR_BLOCKED_BY_CLIENT app.css:1 
Failed to load resource: net::ERR_BLOCKED_BY_CLIENT app.js:1

Any ideas of what I've done wrong or not configured correctly?

Am new to linux/valet-plus as I've converted from a Mac and this worked without issue in my previous environment.

Many thanks for any help and assistance in advance.
Regards
Carl.

**Comment by uttamrabadiya** [comment]
@CarlOgden1967 net::ERR_BLOCKED_BY_CLIENT is mostly from the browser side, but can you share some screenshot and URL that hits failed to load?

**Comment by CarlOgden1967** [comment]
The URL is local, pos-security.test either http or HTTPS I'm just creating a local setup to mess about getting started with laravel and Vue 
Regards, Carl

**Comment by CarlOgden1967** [comment]
After a bit of work in my web app, I did an npm run build, and it then displayed as expected, no errors. When I go and perform npm run dev, the resource files are missing. I'll do further digging to see if it's a permissions issue on the dev files

**Comment by uttamrabadiya** [comment]
Carl,

I believe it's port specific issue, if you could share the URLs & screenshot that are being blocked then I can help you here.

**Comment by CarlOgden1967** [comment]
After further trawling, following this guide fixed the issue:-

https://laravel.com/docs/9.x/vite#working-with-a-secure-development-server
