### ISSUE TITLE
Nginx is stopped...

### ISSUE THREAD

**Issue by bhalawaty** [genesisweb/valet-linux-plus#105]
I checked the Nginx status and found this 

 systemctl status nginx.service

× nginx.service - A high performance web server and a reverse proxy server
     Loaded: loaded (/lib/systemd/system/nginx.service; enabled; vendor preset: enabled)
     Active: failed (Result: exit-code) since Tue 2023-06-06 00:42:21 EEST; 34s ago
       Docs: man:nginx(8)
    Process: 28030 ExecStartPre=/usr/sbin/nginx -t -q -g daemon on; master_process on; (code=exited, status=1/FAILURE)
        CPU: 15ms

systemd[1]: Starting A high performance web server and a reverse proxy server...
nginx[28030]: nginx: [emerg] host not found in upstream "localhost" in /home/user/.valet/Nginx/mails.test:33
nginx[28030]: nginx: configuration file /etc/nginx/nginx.conf test failed
systemd[1]: nginx.service: Control process exited, code=exited, status=1/FAILURE
systemd[1]: nginx.service: Failed with result 'exit-code'.
systemd[1]: Failed to start A high performance web server and a reverse proxy server.

**Comment by uttamrabadiya** [comment]
@bhalawaty 
Could you please share content of /home/user/.valet/Nginx/mails.test file, it seems your mails.test file's config is broken for some reason, it should be some as below:

```
# valet stub: secure.proxy.valet.conf

server {
    listen 80;
    server_name mails.test www. mails.test *. mails.test;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl http2;
    #listen 127.0.0.1:443 ssl http2; # valet loopback
    server_name mails.test www. mails.test *. mails.test;
    root /;
    charset utf-8;
    client_max_body_size 128M;
    http2_push_preload on;

    location /41c270e4-5535-4daa-b23e-c269744c2f45/ {
        internal;
        alias /;
        try_files $uri $uri/;
    }

    ssl_certificate "/home/user/.valet/Certificates/mails.test.crt";
    ssl_certificate_key "/home/user/.valet/Certificates/mails.test.key";

    access_log off;
    error_log "/home/user/.valet/Log/mails.test-error.log";

    error_page 404 "/home/user/.config/composer/vendor/genesisweb/valet-linux-plus/server.php";

    location / {
        proxy_pass http://localhost:8025;
        proxy_set_header   Host              $host;
        proxy_set_header   X-NginX-Proxy     true;
        proxy_set_header   X-Real-IP         $remote_addr;
        proxy_set_header   X-Forwarded-For   $proxy_add_x_forwarded_for;
        proxy_set_header   Upgrade           $http_upgrade;
        proxy_set_header   Connection        "upgrade";
        proxy_set_header   X-Forwarded-Proto $scheme;
        proxy_http_version 1.1;
        proxy_intercept_errors on;
        proxy_request_buffering off;
        proxy_buffering off;
        proxy_redirect off;
    }

    location ~ /\.ht {
        deny all;
    }
}
```

There should be some difference for `proxy_pass ...;`

**Comment by uttamrabadiya** [comment]
@bhalawaty Closing this issue, if you still face any error, feel free to re-open or create new one. Thank you.
