### ISSUE TITLE
Mailpit panel is throwing 502 Bad Gateway

### ISSUE THREAD

**Issue by albus25** [genesisweb/valet-linux-plus#106]
I have started server with `valet start mailpit`. Server started successfully. But I cannot access the panel. I have changed my domain to localhost.

![image](https://github.com/genesisweb/valet-linux-plus/assets/37008711/b6911df2-1b0b-46b3-b45b-ff09eaa9ac05)

**Comment by uttamrabadiya** [comment]
@albus25 
Can you please share output of below commands:
```
sudo lsof -i -P | grep LISTEN
sudo service mailpit status
```
Also if you can share output of below file then it can be easier to understand:
```
cat ~/.valet/Nginx/mails.localhost
```

This issue could be due to service is not running properly or NGINX's proxy_pass could be misconfigured.

Thank you!

**Comment by chandraauliatama** [comment]
@albus25 
did you find a solution to this problem? I am also have this problem

**Comment by chandraauliatama** [comment]
@uttamrabadiya 

# valet stub: secure.proxy.valet.conf

server {
    listen 80;
    server_name mails.test www.mails.test *.mails.test;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl http2;
    #listen VALET_LOOPBACK:443 ssl http2; # valet loopback
    server_name mails.test www.mails.test *.mails.test;
    root /;
    charset utf-8;
    client_max_body_size 128M;
    http2_push_preload on;

    location /41c270e4-5535-4daa-b23e-c269744c2f45/ {
        internal;
        alias /;
        try_files $uri $uri/;
    }

    ssl_certificate "/home/chandraat/.valet/Certificates/mails.test.crt";
    ssl_certificate_key "/home/chandraat/.valet/Certificates/mails.test.key";

    access_log off;
    error_log "/home/chandraat/.valet/Log/mails.test-error.log";

    error_page 404 "/home/chandraat/.config/composer/vendor/genesisweb/valet-linux-plus/server.php";

    location / {
        proxy_pass http://localhost:8025;
        proxy_set_header   Host              $host;
        proxy_set_header   X-NginX-Proxy     true;
        proxy_set_header   X-Real-IP         $remote_addr;
        proxy_set_header   X-Forwarded-For   $proxy_add_x_forwarded_for;
        proxy_set_header   Upgrade           $http_upgrade;
        proxy_set_header   Connection        "upgrade";
        proxy_set_header   X-Forwarded-Proto $scheme;
        proxy_http_version 1.1;
        proxy_intercept_errors on;
        proxy_request_buffering off;
        proxy_buffering off;
        proxy_redirect off;
    }

    location ~ /\.ht {
        deny all;
    }
}

**Comment by chandraauliatama** [comment]
@uttamrabadiya its like mailpit not installed or something
![image](https://github.com/genesisweb/valet-linux-plus/assets/64741857/428bbad1-813c-45a0-b3a3-bb46f62c9972)

**Comment by chandraauliatama** [comment]
its working now

I just need to install mailpit then restart valet

```
sudo bash < <(curl -sL https://raw.githubusercontent.com/axllent/mailpit/develop/install.sh) 
```

**Comment by uttamrabadiya** [comment]
@chandraauliatama Great to hear that! We will release the needful fix for this.
@albus25 Please follow above step to fix your issue and feel free to re-open this issue if it still persist.

**Comment by uttamrabadiya** [comment]
@albus25 @chandraauliatama 

We've fixed Mailpit install issue in our latest release (v1.6.7), please update package to fix this issue.

**Comment by albus25** [comment]
Sorry for the delay, but it is working perfectly in new version. Thank you @uttamrabadiya.
