### ISSUE TITLE
No valet urls working after valet update/downgrade

### ISSUE THREAD

**Issue by Stephan-MC** [genesisweb/valet-linux-plus#110]
i installed the latest version (1.6.7) of valet some days ago and after that, all my valet projects were inaccessible. i also realised that the file ~/.valet/valet82.sock was empty (no content in it). Hope it's not the one disturbing.

I am on Kali (debian 12+)

**Comment by uttamrabadiya** [comment]
@Stephan-MC It's too late to respond here, but you may need to re-use the php version to generate valet82.sock file, please use `valet use php@8.2 --update-cli` command to generate valet82.sock file.

**Comment by Stephan-MC** [comment]
Thanks… 🙏🏿
