### ISSUE TITLE
differences with other packages

### ISSUE THREAD

**Issue by holiq** [genesisweb/valet-linux-plus#111]
Hello, I want to use valet on Linux and I found two package, so what is the difference this package from [cpriego/valet-linux](https://github.com/cpriego/valet-linux) ?

**Comment by uttamrabadiya** [comment]
We are including some extra integrations such as Mailpit, Redis, Subdomains,etc.. You can find more details on https://valetlinux.plus/

**Comment by holiq** [comment]
Wow that looks awesome, thank you
