### ISSUE TITLE
Unable to use .test tld on wsl2

### ISSUE THREAD

**Issue by AbiruzzamanMolla** [genesisweb/valet-linux-plus#112]
I have installed valet-linux-plus on wsl-2 Ubuntu. everything is working fine but i am not able to use *.test domains. so i am also not able to use multiple php version feature of valet.

**Comment by feenx** [comment]
I'm currently working on WSL2 and jus set my Windows' hosts files manually for each domain I intend on using.

**Comment by uttamrabadiya** [comment]
@feenx @AbiruzzamanMolla We do not support WSL Ubuntu so far, as it requires some additional efforts to support custom TLD and other features, I believe Laravel's official Herd package can be a good solution for Windows users.
