### ISSUE TITLE
Bug: Bad Gateway because valet.sock is not created

### ISSUE THREAD

**Issue by abbasmashaddy72** [genesisweb/valet-linux-plus#116]
ValetLinux+ v1.6.7
PHP 8.2.13
Distro: EndeavourOS

I get a 502 Bad Gateway. Looking in the `~/.valet/Log/nginx-error.log` I get `connect() to unix:/home/abbasmashaddy72/.valet/valet.sock`.
In my `~/.valet` directory is only a `valet.sock` which I am unable to read.

```
2023/12/11 12:34:03 [crit] 23783#23783: *45 connect() to unix:/home/abbasmashaddy72/.valet/valet82.sock failed (2: No such file or directory) while connecting to upstream, client: 127.0.0.1, server: , request: "GET / HTTP/1.1", upstream: "fastcgi://unix:/home/abbasmashaddy72/.valet/valet82.sock:", host: "brubick.test"
2023/12/11 12:34:03 [crit] 23783#23783: *45 connect() to unix:/home/abbasmashaddy72/.valet/valet82.sock failed (2: No such file or directory) while connecting to upstream, client: 127.0.0.1, server: , request: "GET /favicon.ico HTTP/1.1", upstream: "fastcgi://unix:/home/abbasmashaddy72/.valet/valet82.sock:", host: "brubick.test", referrer: "http://brubick.test/"
2023/12/11 12:34:04 [crit] 23783#23783: *53 connect() to unix:/home/abbasmashaddy72/.valet/valet82.sock failed (2: No such file or directory) while connecting to upstream, client: 127.0.0.1, server: , request: "GET / HTTP/1.1", upstream: "fastcgi://unix:/home/abbasmashaddy72/.valet/valet82.sock:", host: "kiddo.test"
```

valet{version}.sock it not created + ln also not properly established
![image](https://github.com/genesisweb/valet-linux-plus/assets/55267488/96c50f4f-cb4b-4318-9a88-d415649c8b22)

Permissions for .valet
![image](https://github.com/genesisweb/valet-linux-plus/assets/55267488/6f627862-1673-4c52-b60e-95b6d795ff77)

Can anyone provide me valet{version}.sock file content so that I can test it out if it can fix the issue or not

**Comment by uttamrabadiya** [comment]
@abbasmashaddy72 I am not sure if it is still open issue for you, but you need to re-use php version of your choise. You can simply do it by `valet use php@8.2`.
