### ISSUE TITLE
No sites are working after fresh installation

### ISSUE THREAD

**Issue by f24aalam** [genesisweb/valet-linux-plus#121]
I have just installed the Valet Linux Plus in Linux mint by following the installation steps from the website but no links are working, 

1. the `valet links` command shows the table with links
2. the `valet status` shows PHP and Nginx are running

**Comment by uttamrabadiya** [comment]
@f24aalam Could you please share which site you are trying to access? E.g. my-site.localhost or my-site.test?
Also if you could please share the TLD that you are using, you can find your current tld by `valet domain` command. Additionally, could you please share output of `valet links` command.

**Comment by uttamrabadiya** [comment]
@f24aalam I am closing this as it seems fixed for you, feel free to re-open or create new one.
