### ISSUE TITLE
WordPress Multisite not working

### ISSUE THREAD

**Issue by alexmigf** [genesisweb/valet-linux-plus#122]
I'm in the process of configuring a WordPress multisite network utilizing sub-directories. However, I've encountered an issue where I can only access the dashboard for the main network site and not the dashboard for the sub-site.

Additionally, I noticed a problem with the documentation: the link provided for the full drivers (https://valetlinux.plus/cli/drivers) is not functioning.

**Comment by uttamrabadiya** [comment]
Hey @alexmigf

I haven't tried this personally but I believe you can resolve this issue by adding a custom driver.

We will fix the documentation link for sure, but here is the link on how to configure a custom driver https://valetlinux.plus/#sharing-sites-on-lan

Thanks

**Comment by alexmigf** [comment]
Thanks! I will try that.
