### ISSUE TITLE
How to share local sites?

### ISSUE THREAD

**Issue by mykola-havrylov** [genesisweb/valet-linux-plus#123]
**Remote access without valet share**

Please tell me how it works? "valet share" - is not worked for me(

![image](https://github.com/genesisweb/valet-linux-plus/assets/128697116/79ba2f44-a5ad-49c5-bf85-22a6e9a39c3c)

**Comment by uttamrabadiya** [comment]
@mykola-havrylov 
If I understand your issue correctly then you want to share your local site using `valet share` command, correct? If so then please update ngrok executable file in `~/.config/composer/vendor/valet-linux-plus/bin` directory, for now you can find the latest version from https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-linux-amd64.tgz file, extract this and copy it on given (`~/.config/composer/vendor/valet-linux-plus/bin`) directory.

We are releasing new version to fix this issue so after next release you won't face this issue. 

Thank you.

**Comment by uttamrabadiya** [comment]
@mykola-havrylov We have fixed this issue on our latest release V2. We have upgraded ngrok binary in this update, feel free to update valet.
