### ISSUE TITLE
valet share is not working

### ISSUE THREAD

**Issue by ha-jitendra** [genesisweb/valet-linux-plus#134]
![Screenshot from 2024-06-20 15-20-28](https://github.com/genesisweb/valet-linux-plus/assets/128698456/d29c497d-2a94-4728-8c7e-625dff307a37)

**Comment by uttamrabadiya** [comment]
@ha-jitendra Can you please share below information.

Valet version
OS
content of following file: ~/.config/valet/Nginx/demo.test & ~/.valet/Nginx/demo.test

**Comment by ha-jitendra** [comment]
@uttamrabadiya

Valet version: ValetLinux+ v1.6.9
OS: Ubuntu 24.04 LTS

`server {
    listen 80;
    server_name demo.test www.demo.test *.demo.test;
    return 301 https://$host$request_uri;
}


server {
    listen 443 ssl http2;
    listen 88;
    server_name demo.testdemo.test *.demo.test;
    root /;
    charset utf-8;

    location /41c270e4-5535-4daa-b23e-c269744c2f45/ {
        internal;
        alias /;
        try_files $uri $uri/;
    }

    ssl_certificate /home/jitendra/.valet/Certificates/demo.test.crt;
    ssl_certificate_key /home/jitendra/.valet/Certificates/demo.test.key;

    location / {
        rewrite ^ /home/jitendra/.config/composer/vendor/genesisweb/valet-linux-plus/server.php last;
    }

    location = /favicon.ico { access_log off; log_not_found off; }
    location = /robots.txt  { access_log off; log_not_found off; }

    access_log off;
    error_log /home/jitendra/.valet/Log/demo.testt-error.log;

    error_page 404 /home/jitendra/.config/composer/vendor/genesisweb/valet-linux-plus/server.php;

    location ~ \.php$ {
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        fastcgi_pass unix:/home/jitendra/.valet/valet74.sock;
        fastcgi_index /home/jitendra/.config/composer/vendor/genesisweb/valet-linux-plus/server.php;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME /home/jitendra/.config/composer/vendor/genesisweb/valet-linux-plus/server.php;
    }

    location ~ /\.ht {
        deny all;
    }
}
`

**Comment by uttamrabadiya** [comment]
@ha-jitendra It seems failing with ngrok tunnel, can you please upgrade to Valet V2. It will help to resolve the issue.
