### ISSUE TITLE
Needs Upgrade Guide for v1.6 to v2.0

### ISSUE THREAD

**Issue by iRaziul** [genesisweb/valet-linux-plus#135]
Valet is already installed on my device (Ubuntu 24) and I want to update it to the latest version.
I tried `valet update` to update but it doesn't allow me to update.

Upgrade guide will be a lot helpful.

**Comment by uttamrabadiya** [comment]
@iRaziul Sure, I will prepare one and will put it on website today.

**Comment by uttamrabadiya** [comment]
@iRaziul I've just added upgrade guide in documentation. https://valetlinux.plus/upgrade
Please feel free to ask any question if you face any trouble. Thank you.

**Comment by phit** [comment]
the upgrade will also break previous custom drivers as they are now namespaced and types were added just like in the official valet
unfortunately this wasn't immediately obvious, any page will show a blank 500 without any error.. I only finally figured this out once I added
```
ini_set("display_errors", "1");
error_reporting(E_ALL);
```
to the `.config/composer/vendor/genesisweb/valet-linux-plus/server.php`
