### ISSUE TITLE
Removed /valet-sites?

### ISSUE THREAD

**Issue by bishwajitcadhikary** [genesisweb/valet-linux-plus#136]
I used to use localhost/valet-sites, but it's not working on the latest version anymore. Did you remove the default valet site list page?

**Comment by uttamrabadiya** [comment]
@bishwajitcadhikary Unfortunately yes, we had to remove /valet-sites path in latest version, because it was in conflict to introduce new features, but we will surely reintroduce this feature in our future releases.
