### ISSUE TITLE
valet install fails on Fedora

### ISSUE THREAD

**Issue by vishytk** [genesisweb/valet-linux-plus#35]
Redis package on Fedora is **redis**
Mysql package on Fedora is **mysql-community-server**

$ valet install
Nginx was already enabled
Stopping nginx...
Restarting php-fpm...
Dnsmasq was already enabled
Installing Valet DNS service...
Valet-dns was already enabled
Systemd-resolved was already disabled
Stopping systemd-resolved...
Restarting NetworkManager...
Restarting dnsmasq...
Starting valet-dns...
Restarting nginx...
Installing Mailhog service...
Mailhog has been enabled
Restarting nginx...
Starting mailhog...
[redis-server] is not installed, installing it now via Dnf... 🍻
Last metadata expiration check: 0:00:52 ago on Thu 04 Mar 2021 10:44:53 AM IST.
No match for argument: redis-server
Error: Unable to find a match: redis-server

[mysql-server] is not installed, installing it now via Dnf...

**Comment by phyrasaur** [comment]
I dunno if this helps, if you check the `install()` method, they just hard-code the name. You can check mysql and redis file here:
https://github.com/genesisweb/valet-linux-plus/tree/master/cli/Valet

**Comment by phyrasaur** [comment]
Yeah, I just updated the executable ngrok, but it's still on 2.* And get my key installed there. Not ideal.

**Comment by uttamrabadiya** [comment]
Valet share is working fine, but we are planning to move out from Ngrok and provide better HTTP Tunnel support from the package, which can be more faster and fully open source.

**Comment by uttamrabadiya** [comment]
@phyrasaur We've just fixed this issue in our latest release. Please update your package and run `valet install` command to fix your issue.
