### ISSUE TITLE
Problem during installation

### ISSUE THREAD

**Issue by xartuu** [genesisweb/valet-linux-plus#40]
During installation the dns servers are changed, which results in no internet access. And this causes an error when installing packages with the `apt` command.
[Here](https://gist.github.com/artuupl/c2c89eacc7aadee6bde3c032227564ba) I paste link to my terminal's output.

**Comment by dvmunjapara** [comment]
Sorry for the delayed response,
Seems like dependencies issue, can you try running sudo apt-get update or try with --fix-missing

**Comment by xartuu** [comment]
I close Issue because I am not using [`valet-linux-plus`](https://github.com/genesisweb/valet-linux-plus) but [`valeryan/valet-wsl`](https://github.com/valeryan/valet-wsl). I have Ubuntu 20.04 installed as WSL.
