### ISSUE TITLE
After Cleaning my PC with Stacer Valet is not working.

### ISSUE THREAD

**Issue by MuhammadSaim** [genesisweb/valet-linux-plus#44]
I just clean my package cache and logs from Stacer after restarting none of my hosts is working I recreate the host using the Valet link but nothing happen. I restart the valet but every package restarted perfectly without any issue but the host still, not working.

Please help.

![image](https://user-images.githubusercontent.com/19898499/125449480-c014a808-7336-4056-a3df-aa8fc1cdb7da.png)

**Comment by uttamrabadiya** [comment]
@MuhammadSaim 

Can you please use the below command and write the output here:

**valet domain**

**valet status**

I believe this can be the issue of wrong domain or the web server service is not up.

**Comment by MuhammadSaim** [comment]
This is the output of both commands
![image](https://user-images.githubusercontent.com/19898499/125557709-db343954-7107-42bd-8959-5751f93b8cc5.png)

**Comment by uttamrabadiya** [comment]
@MuhammadSaim  as you can see your nginx service is not running, can you run the below command and paste output of it

sudo service nginx status

lsof -i -T | grep LISTEN

above commands will get the error of nginx as well as who is currently listening to port 80, there might be issue that Apache2 or some other service is running and due to that nginx couldn't start.

**Comment by MuhammadSaim** [comment]
I just solve the nginx issue now its working Stacer delete the log directory of the niginx in the `/var/log/` I just created the directory with the name of `nginx` now it's working well. Now having an issue with MySQL service MySQL is not running.

![image](https://user-images.githubusercontent.com/19898499/125559120-24f66fd0-7e27-48f2-900a-879a94817033.png)

**Comment by dvmunjapara** [comment]
@MuhammadSaim Can you please run sudo systemctl status mysql.service

**Comment by dvmunjapara** [comment]
Can you please check if dir /var/log/mysql/ present?

**Comment by naowas** [comment]
create mysql and nginx log files manually.
