### ISSUE TITLE
Setting password for root user failed.

### ISSUE THREAD

**Issue by zainulhasan** [genesisweb/valet-linux-plus#47]
Unable to set DB password. Have tried my solution provided on the internet but still not working.

I am popos latest version

**Comment by zainulhasan** [comment]
> Can you tell me the error you are getting while setting the password?

When I do fresh install. and valet install MySQL its it shows **Setting password for root user failed** this error

**Comment by dvmunjapara** [comment]
Can you run follwoing commands

```
sudo mysql
ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY 'password';
```
