### ISSUE TITLE
`valet use` command failing on Arch Linux

### ISSUE THREAD

**Issue by NikarashiHatsu** [genesisweb/valet-linux-plus#49]
**OS details**
Arch Linux x86_64
Kernel 5.14.2-arch1-2
DE Plasma 5.22.5

**How to reproduce**
1. Run `valet use 7.4`

**Error**
The command simply fails and says: `Pacman was unable to install [php7.4-fpm]`.

**Expected**
Valet changes the PHP version to 7.4.

Screenshot below
![Screenshot_20210927_014117](https://user-images.githubusercontent.com/43662951/134820274-79d6c34e-1e40-42a7-b1fc-a5c22dad58e0.png)

I know it's probably a OS compatibility, but I can't figure out any workaround. The best I've tried is to downgrade `php-cli` and `php-fpm` using pacman, didn't work, even after running `valet restart` and rebooting the machine.

**Comment by cobraprojects** [comment]
you can just edit `valet` configration files to fix these issues with `archlinx`

configration files ar in your home directory:
`~/.config/composer/vendor/genesisweb/valet-linux-plus/cli/Valet/`

you need to edit `ValetRedis.php` with your favourite text editor and replace all `redis-server` with `redis`

if you are using `mariadb` edit `Mysql.php`
and replace all `mysql-service` with `mariadb`

**Comment by NikarashiHatsu** [comment]
Hi, it's been a while since I opened this issue.

Currently I'm reverting back to the original Valet Linux, so this issue is already irrelevant.

It is already mentioned that I can simply switch PHP version using `use 8` or `use74`. Thanks a lot for contributors here for help, I really appreciate it. I'm closing this issue.
