### ISSUE TITLE
Failed to connect to MySQL

### ISSUE THREAD

**Issue by stoneC0der** [genesisweb/valet-linux-plus#52]
Hi,
I unable to install valet with mysql 5.7 already install, I might want to remove and install along with valet-linux but can't this be solved,

Looks like MySQL already installed to your system, please enter MySQL [root] user password to connect MySQL with us:

is where I am stuck, I can successfully log into mysql with:

mysql -h 127.0.0.1 -P 3306 -u root -p

so mysql itself work perfectly

**Comment by phyrasaur** [comment]
I had a different problem but similar. You can change `valet db:password` to override the old one. The default password is `root` saved [here](https://github.com/genesisweb/valet-linux-plus/blob/1f99b9fce9dd03c80f187e59469dbac4f6350ebb/cli/Valet/Mysql.php#L16)

**Comment by uttamrabadiya** [comment]
@stoneC0der @phyrasaur 

We apolgoize for the delayed response, we have start upgrading this project again, we will post new release soon to fix MySQL connection and Ngrok support.

**Comment by phyrasaur** [comment]
@uttamrabadiya Well the code is kinda easy to understand. I just changed the internals myself.😆

**Comment by uttamrabadiya** [comment]
Great, thank you :)

**Comment by stoneC0der** [comment]
I had to another valet-linux untill now, I will give another go thanks @phyrasaur @uttamrabadiya
