### ISSUE TITLE
In the PHP 8.0 phpmyadmin is not working

### ISSUE THREAD

**Issue by bhavesh1992** [genesisweb/valet-linux-plus#57]
Hello Team

I switched to PHP 8.0 then PHPMyAdmin is not working. please check the below screenshot.

![image](https://user-images.githubusercontent.com/16099826/181159766-b53be4b2-5342-40f5-afb6-9ec3ca9bca2d.png)

Thanks

**Comment by uttamrabadiya** [comment]
Hey Buddy!

Sorry for the delay, but if you are still facing this issue, could you please share **nginx-error.log** file, this file is located in **.valet/Log** directory.
