### ISSUE TITLE
Redis Server Installation Issue Pacman

### ISSUE THREAD

**Issue by abbasmashaddy72** [genesisweb/valet-linux-plus#58]
![image](https://user-images.githubusercontent.com/55267488/187569926-9aa83b3c-265d-41dc-9874-8e9f5f2b1dbb.png)

How to fix it??

@scrutinizer-auto-fixer @dvmunjapara @StyleCIBot @uttamrabadiya

**Comment by uttamrabadiya** [comment]
I haven't recently tried with Pacman, will give it a shot, I believe they have different name than redis-server.

**Comment by abbasmashaddy72** [comment]
Okay, Thanks for the Reply

I will be Waiting

**Comment by nillegal** [comment]
Facing the same issue, looks like `redis-server` is not available on Pacman. I found out it could possibly be installed with [Snap](https://snapcraft.io/install/redis/manjaro) by Valet Linux Plus is always looking for `redis-server`. The issue always persists.

**Comment by uttamrabadiya** [comment]
Yes, we are working on it, we will release update soon to fix it for all package managers.

**Comment by abbasmashaddy72** [comment]
Thanks waiting for update

**Comment by abbasmashaddy72** [comment]
In pacman only redis is available I think redis is similar to redis-server

**Comment by markovic-nikola** [comment]
While we wait for dev's fix, in case you don't need redis, you can comment out the installation method(s) in order to skip it.
File: `cli/Valet/ValetRedis.php`

**Comment by abbasmashaddy72** [comment]
Okay I think Every is fixed in new update it is working fine in my PC

**Comment by uttamrabadiya** [comment]
@abbasmashaddy72 @markovic-nikola @nillegal 

Just to update in here, we've just released new version to fix this issue. Now we are reading package name by Package provider so it will fix this issue.

Thank you.

**Comment by abbasmashaddy72** [comment]
I will Check it out @uttamrabadiya

Thanks.
