### ISSUE TITLE
Ubuntu 22.04 connectivity issues

### ISSUE THREAD

**Issue by AboElnoor** [genesisweb/valet-linux-plus#63]
I've installed it on upgraded Ubuntu 22.04.

I have the following issues:
1- Valet sometimes stops working, so I restart it to make it work again.
2- It affects firefox and Postman connection to the internet, even when all services are working well. (It works when I restart Valet)

Any suggested solutions here?

**Comment by uttamrabadiya** [comment]
@AboElnoor Facing the same issue, it is something with **dnsmasq** service that we use for custom domains, I am working on it, will keep you posted for the solution.

**Comment by Azim-Sabbir** [comment]
> I've installed it on upgraded Ubuntu 22.04.
> 
> I have the following issues: 1- Valet sometimes stops working, so I restart it to make it work again. 2- It affects firefox and Postman connection to the internet, even when all services are working well. (It works when I restart Valet)
> 
> Any suggested solutions here?

im facing the same issue here

**Comment by uttamrabadiya** [comment]
@Azim-Sabbir This is due to dnsmasq, and we are having bit of uncertainity due to other priorites but we will release this fix very soon. Thanks!

**Comment by AboElnoor** [comment]
@uttamrabadiya Hi,

I like to mention something that I wish it's helpful.
When we installed valet with php8.1, running valet stopped the internet connection for all services, but installation with php7.4 kept the internet running except for some services like firefox and postman.

Anyway, the installation with 7.4 is much better and more stable. I hope this info helps you.
Thank you so much for this gorgeous tool.

Regards,

**Comment by AboElnoor** [comment]
@uttamrabadiya Thank you so much for your help, but I believe this issue should still be open as the main issue still exists.
I was sending a hint that may help you solve the main issue.

And please let me know if there is anything I can do to help solve this.
Thanks for your effort and understanding.

Regards,

**Comment by uttamrabadiya** [comment]
@AboElnoor Thank you, I've started looking at it but I am not able to reproduce it with php8.1, but yes we will figure it out. Keeping it open till we resolve it.

**Comment by uttamrabadiya** [comment]
@AboElnoor @Azim-Sabbir 

Great news guys, we have fixed the connectivity issue. This issue was due to **dnsmasq** & **systemd-resolved** services, systemd-resolved controls internet, so we cannot turn it down, we've just modified our code to keep **systemd-resolved** up and running along with **dnsmasq**. 

Please update to latest version and run `valet install` command to fix this issue.

Feel free to re-open this if your issue persist.

Thank you!

**Comment by AboElnoor** [comment]
@uttamrabadiya Thank you so much for your great effort in helping with this.

I've found a related issue to this issue when switching the wifi network, the valet websites and firefox stop working, and I have to restart the valet to make it run again. Should I open a new issue for this? Or would you like to reopen this issue till you fix this?

Regards,

**Comment by uttamrabadiya** [comment]
@AboElnoor thats strange, I will look into it.

**Comment by uttamrabadiya** [comment]
@AboElnoor 

After testing this on multiple device, I've found the issue, there is something wrong with file watchers in `valet-dns` service.

I am trying further to resolve it ASAP but I believe it will take bit more time. I will keep you posted if I can release new patch soon.

Regards.

**Comment by uttamrabadiya** [comment]
@AboElnoor Final thought before I signoff for today.

I believe valet can work without valet-dns service! I just realized that with using systemd-resolved service, we don't need to add local dns records on dnsmasq, so even if we turn off valet-dns service, it will work just fine.

You can try turning down valet-dns service by following

```
systemctl stop valet-dns
systemctl disable valet-dns
```

**Note:** We are restarting this service on `install` command so if you are using `valet install` command, then please run above command afterwards to disable it again.

**Comment by AboElnoor** [comment]
@uttamrabadiya Thank you so much.

Yes, everything works excellently after disabling it.
I'm wondering why we use it if it's not needed.

Regards,

**Comment by uttamrabadiya** [comment]
@AboElnoor 

It was needed without `systemd-resolved` service to grab the local dns records in dnsmasq, but with using `dnsmasq` and `systemd-resolved` both we do not need to keep `valet-dns` service. We will remove this on our next release.
Keeping this comment open till then.

Thank you!

**Comment by cobraprojects** [comment]
after disabling `valet-dns` and `systemd-resolved` 
using only `dnsmasq` all issues was solved https://github.com/genesisweb/valet-linux-plus/issues/77 and https://github.com/genesisweb/valet-linux-plus/issues/74

**Comment by uttamrabadiya** [comment]
@bkno @cobraprojects @AboElnoor @Azim-Sabbir 

Thank you for being patient with connectivity issues, we've released new version (1.6.3) which updates configuration for dnsmasq, systemd-resolved and also removes the valet-dns as it is not needed anymore, please update to latest version to fix this issue.
