### ISSUE TITLE
How to change the default config directory?

### ISSUE THREAD

**Issue by balduinofernando** [genesisweb/valet-linux-plus#72]
Hi!
I use valet on macOS and the default config folder is located at the home directory is in 

> `~/.config/valet`

But in valet-linux-plus it is in the home directory

> `~/.valet` 

------

The main problem is that I have some settings in a project, and I get check certificates in the Certificates folder, and they have different paths as seen before, so I want to have one path on both operating systems if I switch my workflow into mac or linux.

How to change the default config directory?

Thanks in advance.

**Comment by uttamrabadiya** [comment]
@balduinofernando Nice idea, 

You need to modify two files to change a default path from `~/.valet` to `~/.config/valet`.

https://github.com/genesisweb/valet-linux-plus/blob/master/valet#L89
https://github.com/genesisweb/valet-linux-plus/blob/051051e8d4ee42ba747a86cad2d5a5ba10469b5e/server.php#L6

We will try to unify it from our package in our next package.

**Comment by balduinofernando** [comment]
Thanks for the tip. 

So I guess I'll have to do it everytime I make an upgrade of the composer packages.

**Comment by uttamrabadiya** [comment]
@balduinofernando 
It won't be so long, we will release this configuration in our next release. 

Thank you!
