### ISSUE TITLE
Manjaro - Valet DB commands issue

### ISSUE THREAD

**Issue by shomsy** [genesisweb/valet-linux-plus#73]
Hello, 

Question, please. Do you know how I can solve this problem? I previously installed MariaDB and set up user privileges but I can't use any of these cool DB commands. 

![image](https://user-images.githubusercontent.com/3872827/215353145-8e1acc16-37b7-4fd0-8606-55616f129b77.png)

I couldn't even install MariaBD with `valet install --mariadb` , so I did it manually.

![image](https://user-images.githubusercontent.com/3872827/215353309-3d6ea3a2-d14c-4b6f-a883-30243813a31c.png)

Any ideas?

**Comment by shomsy** [comment]
Oh, ok. The errors on the first screenshot are solved by loading the `mysql_pdo` extension (I forgot to reload PHP).
The second one, installing MySQL, is still a problem. So the solution is to do it manually and ignore this error, you `can` start the Valet.

**Comment by uttamrabadiya** [comment]
@shomsy 
It seems your problem is resolved, but we are going to enhance this integration in our next release. Cloud you please share some more details such as your Operating System, PHP & Composer versions. 

Thanks in advance!

**Comment by cobraprojects** [comment]
maually edit `/home/cobra/.config/composer/vendor/genesisweb/valet-linux-plus/cli/Valet/Mysql.php`

and comment these lines
```
if (!extension_loaded('mysql')) {
    $phpVersion = \PhpFpm::getVersion(true);
    $this->pm->ensureInstalled("php{$phpVersion}-mysql");
}
```

will solve the issue, as extension `mysql` is no longer needed 


other solution is to enable `myql` extension in your php.ini file

**Comment by cobraprojects** [comment]
yeah `yay` or `paru` would but not for all php versions
if it's ok for you it might not work for others

**Comment by shomsy** [comment]
Sure, just described my problem from the images above :)

**Comment by markovic-nikola** [comment]
Same issue for me on Manjaro.
I followed @cobraprojects workaround as a temporary solution.

Although, I already have PHP installed through Pacman.
`php 8.2.2-1`
`php-fpm 8.2.2-1`
