### ISSUE TITLE
i cant run on offline

### ISSUE THREAD

**Issue by hosamalzagh** [genesisweb/valet-linux-plus#74]
valet-linux-plus not work on offline  newtwork must connect with WiFi  (with or without internet) just  connect with any network 

my system is arch

**Comment by uttamrabadiya** [comment]
@hosamalzagh We will look into it. Will keep you posted.

**Comment by hosamalzagh** [comment]
@uttamrabadiya some time value stop work suddenly ,
and to fix must run valet install again or just disconnect network and reconnect again 
my os is arch

**Comment by cobraprojects** [comment]
> valet-linux-plus not work on offline newtwork must connect with WiFi (with or without internet) just connect with any network
> 
> my system is arch

Same issue using archlinux with Kde desktop

**Comment by uttamrabadiya** [comment]
@cobraprojects @hosamalzagh 

Just to share an update here, We haven't found any clue regarding this failure on Arch Linux, something is wrong with dnsmasq or systemd-resolved service as they are not functioning as same as they do on Ubuntu OS, we will continue work on this and will share update if we have any progress here.

Thank you!

**Comment by hosamalzagh** [comment]
@uttamrabadiya you fix it work fine offline

**Comment by Stephan-MC** [comment]
```bash
valet domain localhost
```

this fixed the problem for me....
