### ISSUE TITLE
Not updating

### ISSUE THREAD

**Issue by carlos-mora** [genesisweb/valet-linux-plus#76]
Hey guys! Thanks for this amazing thing!
I need some help with updating Valet. According to itself, it needs an upgrade:
```
vant@AGILE:~/projects/e-cases/web$ valet is-latest
NO

```
but upgrade doen't change things:
```

vant@AGILE:~/projects/e-cases/web$ valet update
There is a new release of Valet Linux
Updating now...
Changed current directory to /home/vant/.config/composer
Loading composer repositories with package information
Updating dependencies
Nothing to modify in lock file
Installing dependencies from lock file (including require-dev)
Nothing to install, update or remove
Generating autoload files
12 packages you are using are looking for funding.
Use the `composer fund` command to find out more!
No security vulnerability advisories found
[sudo] contraseña para vant:      
Nginx was already enabled
Stopping apache2...
Stopping nginx...
Restarting php5.6-fpm...
Dnsmasq was already enabled
Installing Valet DNS service...
Valet-dns was already enabled
Restarting systemd-resolved...
Restarting dnsmasq...
Restarting valet-dns...
Restarting nginx...
Installing MailHog service...
Mailhog was already enabled
Restarting nginx...
Starting mailhog...
Redis-server was already enabled

Valet installed successfully!
vant@AGILE:~/projects/e-cases/web$ valet is-latest
NO
```
Is upgrade the right way to update?

Thanks!

**Comment by dvmunjapara** [comment]
Thank you for your support,

I will look into this and keep you posted

**Comment by dvmunjapara** [comment]
You are already on the latest version which is 1.6.0, Found an issue with the version check, we will address it on the next release

**Comment by carlos-mora** [comment]
Thanks! Yes, you are right, I'm in 1.6.0. 
Just having some issues with dnsmasq when my laptop goes into sleep mode, and I was trying to be sure I'm on the latest release.

Thanks for such an amazing job!

**Comment by uttamrabadiya** [comment]
@carlos-mora We have updated configuration for dnsmasq, I believe this should fix internet disconnection related issue, please update to latest version (1.6.3).

Thank you!

**Comment by carlos-mora** [comment]
I've updated right now. Thanks guys for your support, you are amazing!

KR
