### ISSUE TITLE
Can you add mailpit?

### ISSUE THREAD

**Issue by bishwajitcadhikary** [genesisweb/valet-linux-plus#86]
[Mailpit](https://github.com/axllent/mailpit)

Mailpit is a multi-platform email testing tool 7 API for developers.

It acts as both an SMTP server, and provides a web interface to view all captured emails.

Mailpit is inspired by [MailHog](https://github.com/axllent/mailpit#why-rewrite-mailhog), but much, much faster.

**Comment by SupianIDz** [comment]
+1

**Comment by uttamrabadiya** [comment]
Definitely +1! Never knew about Mailpit, surely we will move to Mailpit on our next release. 

Thank you!

**Comment by uttamrabadiya** [comment]
@bishwajitcadhikary @SupianIDz We have replaced Mailhog with Mailpit as a default mailbox in our latest release v1.6.6.

**Comment by bishwajitcadhikary** [comment]
Thank you.
