### ISSUE TITLE
Unable to isolate a specific version of PHP

### ISSUE THREAD

**Issue by SupianIDz** [genesisweb/valet-linux-plus#87]
![image](https://user-images.githubusercontent.com/37969970/227525764-d4a5ed97-ad8f-402e-b4e7-7ff8b6b2a589.png)

I also can't find the documentation to set the version specifically. I conclude there is no this feature but the command is still there.

I think this is really necessary, because there must be someone working on a project with a different PHP version, it's inconvenient when you have to switch between PHP versions when doing other projects.

Thanks for making this, I like the subdomains, mail and database features but I don't think I can work comfortably without `isolation`.

**Comment by uttamrabadiya** [comment]
@SupianIDz 
We've fixed this issue, and will be included in our next release. Thank you!
