### ISSUE TITLE
no valet url working on fedora

### ISSUE THREAD

**Issue by sacsbrainz** [genesisweb/valet-linux-plus#92]
This site can’t be reachedmailhog.test’s server IP address could not be found.
Try:

Checking the connection
[Checking the proxy, firewall, and DNS configuration](chrome-error://chromewebdata/#buttons)
ERR_NAME_NOT_RESOLVED

**Comment by uttamrabadiya** [comment]
@sacsbrainz 
Try with `mailhog.localhost` domain, we have noticed multipel inconsitancies with custom domain support.

**Comment by uttamrabadiya** [comment]
@sacsbrainz We have fixed this issue in V2 release, feel free to update and let us know if you have any issue.
