### ISSUE TITLE
Both Mailhog and Mailpit Do Not Work in version 1.6.6

### ISSUE THREAD

**Issue by lukastom** [genesisweb/valet-linux-plus#98]
After upgrading to version 1.6.6, mailhog.test gives 502 Bad Gateway. Did we actually move to Mailpit? Is there any replacement for mailhog.test? I tried mailpit.test but that gives 404 error, http://0.0.0.0:8025 does not exist, `valet open mailpit` gives 404. Also Valet Linux Plus documentation probably needs adjusting, so we know, what is the proper configuration for Mailpit to work.

**Comment by uttamrabadiya** [comment]
@lukastom Yes, we moved it to Mailpit, and you can access it via mails.test domain. Yes we are working to update documentation.

**Comment by shankhadevpadam** [comment]
@uttamrabadiya still not working 404 not found.

**Comment by conradmaaijen** [comment]
Hi,

I had to install Mailpit manually after installing valet-linux+

Then: valet start mailpit and see your send mails on /mails


¯\_(ツ)_/¯

Conrad Maaijen

**Comment by uttamrabadiya** [comment]
@conradmaaijen 
You do not need to install it manually, but can you please share output of below mentioned commands:

```
sudo systemctl status mailpit
sudo lsof -i -P | grep LISTEN
cat ~/.valet/Log/mails.test-error.log
cat ~/.valet/Log/nginx-error.log
```

**Comment by uttamrabadiya** [comment]
@lukastom @conradmaaijen 
We've fixed Mailpit install issue in our latest release (v1.6.7), please update package to fix this issue.
